// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNdaKbrdqZeCQh1ENwdSHUm9yQ5PNQbOU',
    appId: '1:381897443766:web:72ac694de0fb5866a39917',
    messagingSenderId: '381897443766',
    projectId: 'chat-app-e61da',
    authDomain: 'chat-app-e61da.firebaseapp.com',
    storageBucket: 'chat-app-e61da.firebasestorage.app',
    measurementId: 'G-3PN5SHRB3D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPXqjk3XE19K1Og_mmlqPA0gNPBTQVc0o',
    appId: '1:381897443766:android:e9cff2d4f9195d38a39917',
    messagingSenderId: '381897443766',
    projectId: 'chat-app-e61da',
    storageBucket: 'chat-app-e61da.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOywqybrqDx1vWw_XmCS3fv6m8avs_NtA',
    appId: '1:381897443766:ios:6a1fd481aea7d2dca39917',
    messagingSenderId: '381897443766',
    projectId: 'chat-app-e61da',
    storageBucket: 'chat-app-e61da.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOywqybrqDx1vWw_XmCS3fv6m8avs_NtA',
    appId: '1:381897443766:ios:6a1fd481aea7d2dca39917',
    messagingSenderId: '381897443766',
    projectId: 'chat-app-e61da',
    storageBucket: 'chat-app-e61da.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );
}
